// 从最终证据填入报告测量区；不把未结束阶段的进度文件作为结果。
import fs from 'node:fs';
import path from 'node:path';
const target=path.resolve(import.meta.dirname,'../../docs/investigations/phase-2-search-architecture-full-dataset-investigation.md');
const evidence=JSON.parse(fs.readFileSync(path.resolve(import.meta.dirname,'../../docs/investigations/evidence/phase-2-search-measurements.json')));
let report=fs.readFileSync(target,'utf8');
const n=x=>Number(x).toLocaleString('en-US'), ms=x=>Number(x).toFixed(2), gib=x=>(x/1024**3).toFixed(2);
const mean=a=>a.reduce((n,v)=>n+v,0)/a.length;
const warm=q=>q?ms(mean(q.timing.warmMs)):'—';
function section(name,text){const start=`<!-- ${name}:start -->`,end=`<!-- ${name}:end -->`,a=report.indexOf(start),b=report.indexOf(end);if(a<0||b<a)throw new Error('REPORT_MARKER');report=report.slice(0,a+start.length)+'\n'+text+'\n'+report.slice(b);}
const baseline=evidence.queries.baseline,opt=evidence.queries['C-optimized'];
const get=(list,label,variant)=>list.find(q=>q.label===label&&(!variant||q.variant===variant));
section('decision-measurements',`字典优先 C 的 string Contains \`Avatar\` 重复均值 ${warm(get(opt,'ascii'))} ms；A/B/naive C 分别 ${['A','B','C'].map(v=>warm(get(baseline,'ascii',v))).join(' / ')} ms。初始 C 的 string 查询已采用 SCAN dictionary + facts_dict，但 VALUE 零结果查询为 ${warm(get(baseline,'zero','C'))} ms，强制顺序字典扫描后为 ${warm(get(opt,'zero'))} ms；schema 本身不足以保证快查询，planner 必须验证实际访问顺序。\n\n推荐 V1 默认完整 C literal 路径，**不默认启用 trigram**：全量 scalar trigram 原生崩溃，不能视为完整成功候选。已完成的 literal 与成功 accelerator 集合差分见第9节；unicode61/LIKE 的不一致和失败 accelerator 均保留。`);
const statsMap=new Map(evidence.textMapPayload.sources.map(s=>[s.path,s]));
section('textmap','| 来源 | raw bytes | FIELD+VALUE | parse+insert wall ms | B 逻辑 payload bytes |\n| --- | ---: | ---: | ---: | ---: |\n'+evidence.textMap.map(s=>`| ${s.path.replace('TextMap/','')} | ${n(s.bytes)} | ${n(s.facts)} | ${ms(s.totalMs)} | ${n(statsMap.get(s.path).logicalPayloadBytes)} |`).join('\n')+'\n\nB 逻辑载荷=text + exact_key + pointer_key 的 UTF-8 bytes，全语言/分片已测，排除 row/index/page overhead；C 的共享字典与物理页不能按该数字直接分摊。');
section('temp','| schema | 重建秒 | DB high GiB | WAL high GiB | temp high GiB（观测） | 最大 temp 文件数 / stat失败 |\n| --- | ---: | ---: | ---: | ---: | ---: |\n'+evidence.tempIndexRecreation.measurements.map(t=>`| ${t.variant} | ${ms(t.wallMs/1000)} | ${gib(t.dbHighBytesObserved)} | ${gib(t.walHighBytesObserved)} | ${gib(t.tempPeakBytesObserved)} | ${t.maxFiles} / ${t.statFailures} |`).join('\n')+'\n\n三库均捕获到非零临时文件峰值。100ms采样会遗漏短暂峰值，stat失败为文件关闭竞态（A/B/C分别2/1/2次）；这些数字是观测下界，不能相加宣称同一时刻的完整物理磁盘峰值。C重建时DB的12.39 GiB包含前序FTS留下的可复用free pages，初始base C仍为10.91 GiB。');
section('publication','同一 '+n(evidence.publicationComparison.outcomes[0].fixtureBytes)+' bytes 自有 fixture 对照整源 replacement transaction 与 chunk staging；两者先独立提交已知 stale 门控，再开始候选写入。独立 WAL reader 在全部chunk边界均看到current=0，完整发布后才见新rows；取消不发布，final-publication crash exit99回滚。\n\n| 策略 | 场景 | attempted rows | current rows | wall ms | chunk SQL累计max ms | 请求到停止 ms |\n| --- | --- | ---: | ---: | ---: | ---: | ---: |\n'+evidence.publicationComparison.outcomes.filter(o=>o.wallMs!==undefined).map(o=>`| ${o.policy} | ${o.scenario} | ${n(o.rowsAttempted)} | ${n(o.currentRows)} | ${ms(o.wallMs)} | ${ms(o.maxChunkSqlMs)} | ${o.cancelRequestToStopMs===null?'—':ms(o.cancelRequestToStopMs)} |`).join('\n')+'\n\n这些小fixture数字用于验证事务/visibility边界，不是全库增量吞吐；staging将事务长度约束在chunk级，增加候选版本门控和回收职责。两者都必须在长事务之外先提交stale，不能期待未提交状态隐藏reader眼中的旧current。');
const initialCancel=evidence.edges.results.find(o=>o.scenario==='cancel initial parsing');
const incrementalCancel=evidence.lifecycle.outcomes.find(o=>o.scenario==='cancel incremental');
section('cancellation',`初始 parsing 请求到停止 ${ms(initialCancel.cancelLatencyMs)} ms；增量 fixture ${ms(incrementalCancel.cancelLatencyMs)} ms，均不发布 complete。早期probe仅记录timer20ms后的总耗时，不能将总耗时等同取消响应；另行补测真实timer回调中的请求时间，包括B前段、后段TextMap区域与C字典：\n\n| representation / 起点 | batch | 扫描rows | timer实际发出ms | 请求到停止ms | 最大同步SQL ms |\n| --- | ---: | ---: | ---: | ---: | ---: |\n`+evidence.queryCancellation.outcomes.map(o=>`| ${o.variant} / ${o.label} | ${n(o.batch)} | ${n(o.scanned)} | ${ms(o.timerRequestObservedMs)} | ${ms(o.cancelRequestToStopMs)} | ${ms(o.maxSqlMs)} |`).join('\n')+'\n\n均为cancelled/complete=false；计时从timer实际执行后算起，之前的event loop阻塞另由timer延迟和最大同步SQL反映。count-only有界probe不是posting merge、全库p95、IPC/UI取消或SLA。');
const connection=evidence.queryCancellation.connections;
report=report.replace('<!-- cancellation:end -->','\n连接重开另测：\n\n| schema | 三次open+PRAGMA ms | 对应首次VALUE Exact 1001 SQL ms |\n| --- | --- | --- |\n'+['A','B','C'].map(v=>`| ${v} | ${connection.filter(c=>c.variant===v).map(c=>ms(c.openIncludingPragmasMs)).join(' / ')} | ${connection.filter(c=>c.variant===v).map(c=>ms(c.firstQueryMs)).join(' / ')} |`).join('\n')+'\n\n每次新建连接且native模块已加载，OS cache仍未清空。查询证据字段firstConnectionObservationMs是同连接每个query的首次SQL采样，不包含new connection耗时，不称冷读。\n<!-- cancellation:end -->');
section('queries','重复均值单位 ms；完整 query plan、首次/两次重复、候选与最终集合差分见 JSON。表中 C-naive 保留初始 join 策略，C-first 为字典优先。\n\n| query / scope / match | truth count | A | B | C-naive | C-first |\n| --- | ---: | ---: | ---: | ---: | ---: |\n'+evidence.sourceReference.queries.map(q=>`| ${JSON.stringify(q.query).replaceAll('\ufeff','\\uFEFF').replaceAll('|','\\|')} / ${q.scope} / ${q.match} | ${n(q.count)} | ${warm(get(baseline,q.label,'A'))} | ${warm(get(baseline,q.label,'B'))} | ${warm(get(baseline,q.label,'C'))} | ${warm(get(opt,q.label))} |`).join('\n'));
const accelNames=['unicode61','trigram-all','trigram-string','trigram-large','trigram-all-ordered','trigram-string-ordered','trigram-large-ordered'];
const acceleratorEntries=accelNames.map(name=>[name,evidence.queries[name]]);
if(evidence.ftsQueryPlans.status==='failed')acceleratorEntries.push(['string-only ordered / plans rebuild',evidence.ftsQueryPlans]);
let text='| accelerator | 字典内容数 | eligible occurrences | used GiB | base C + used / base C | 建立秒 | Avatar ms | 拍 ms | 最终 FN / FP 合计 |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |\n';
for(const [name,a] of acceleratorEntries){if(a.status==='failed'){text+=`| ${name} FAILED | ${n(a.lastCommitted.rows)}（部分） | — | — | — | ${ms(a.failure.wallMs/1000)} 后失败 | — | — | 未完成，不能证明 |\n`;continue;}text+=`| ${name} | ${n(a.indexedDictionaryRows)} | ${n(a.eligibleOccurrences)} | ${gib(a.acceleratorUsedBytes)} | ${(1+a.acceleratorUsedBytes/evidence.variants.C.final.db).toFixed(3)}× | ${ms(a.buildMs/1000)} | ${warm(get(a.results,'ascii'))} | ${warm(get(a.results,'chs-1'))} | ${n(a.results.reduce((n,q)=>n+q.proof.falseNegative,0))} / ${n(a.results.reduce((n,q)=>n+q.proof.falsePositive,0))} |\n`;}
const like=evidence.queries['C-like'];
text+='\nLIKE 全库大小写反例：`Avatar` 的 literal truth '+n(get(like,'ascii').count)+'，LIKE 最终 false positive '+n(get(like,'ascii').proof.falsePositive)+'、false negative '+n(get(like,'ascii').proof.falseNegative)+'；没有把此路径推荐成 literal contract。\n';
const tri=evidence.queries['trigram-string-ordered'],large=evidence.queries['trigram-large-ordered'];
text+=`\nstring-only 对 Avatar 相对 C-first count 的加速比 ${(mean(get(opt,'ascii').timing.warmMs)/mean(get(tri.results,'ascii').timing.warmMs)).toFixed(1)}×；cp≥256大文本只覆盖其142个命中，其余174,359个走fallback，因此同查询加速比 ${(mean(get(opt,'ascii').timing.warmMs)/mean(get(large.results,'ascii').timing.warmMs)).toFixed(2)}×。1–2code-point与FIELD继续完整扫描。成功string-only的额外build时间为原C物化时间的 ${(tri.buildMs/evidence.variants.C.fullWallMs).toFixed(3)}×；这只是附加阶段成本，不能当direct-from-raw端到端build multiplier。\n`;
text+=`\n候选建议：默认保留完整 C-first 扫描和 typed Exact；**不默认启用 trigram**。string-only 对 Avatar 的重复均值 ${warm(get(tri.results,'ascii'))} ms，大文本策略为 ${warm(get(large.results,'ascii'))} ms；失败策略的空白是未证明，不能当零延迟。成功策略的速度与磁盘收益仍值得后续评审，但原生崩溃根因、可取消构建/merge、生产浏览竞争和 Mac gate 关闭前，不把它作为依赖。\n\ntrigram-all 在提交至 dictionary id6,500,000、5,904,220 eligible rows 后，以0xC0000005退出；未执行最终查询。缓存 quick_check=ok，失败下一批6,500,001–6,525,000（25,000条，max12,987 code points）在新的小 FTS 库成功。这个对照没有复现单批失败，也没有解释全库崩溃；根因继续 **OPEN / REQUIRES FOLLOW-UP**，不是 SQLite bug 或硬件故障的已证结论。`;
text+='\n\n实际原型 INSERT SELECT 走字典 class/kind 索引，25k id 范围内返回文本顺序的非递增 rowid，也反复访问大范围字典。新对照强制 NOT INDEXED + ORDER BY id，query plan变为 INTEGER PRIMARY KEY 范围扫描；全 scalar有序对照仍在83.57秒、已提交6,504,218条/id7,100,000后原生崩溃，RSS最近checkpoint约88MiB、SQL批次max1.09秒。访问顺序问题已证实，崩溃根因未关闭，不能把它简单归因于排序或OOM。两类原型完整终态均在表与证据中保留。';
text+='\n\n首轮成功FTS没有持久化最终查询计划。为补齐该项，另行完整重建有序string-only，但在93.50秒、已提交3,858,216条/id7,275,000后同样0xC0000005退出；quick_check=ok。首轮集合验证仍有效，**string-only稳定性也不能宣称已证**。不再重建FTS；只在隔离的partial accelerator上采集EXPLAIN，明确未执行查询、未证明完整计划。完整FTS查询计划继续OPEN，partial计划不能冒充成功全量计划。';
section('accelerator',text);
let runtimeText='';
for(const [label,r] of [['Node',evidence.runtimeNode],['Utility',evidence.runtime]]){
  runtimeText+=`**${label}**\n\n| harness / phase / 操作 | 次数 | wall 中位 ms | wall max ms | parser queue max ms | parser execution max ms |\n| --- | ---: | ---: | ---: | ---: | ---: |\n`;
  for(const phase of ['baseline','under full indexing','large source head-of-line'])for(const op of ['listDirectory','getSourceInfo','readNode','listNodeChildren','readScalarSegment','source activation']){
    const a=r.observations.filter(x=>x.phase===phase&&x.operation===op),queue=r.queueObservations.filter(x=>x.phase===phase&&x.operation===op&&x.lane==='parserQueue');if(!a.length)continue;
    const sorted=a.map(x=>x.ms).sort((a,b)=>a-b),median=sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2;
    runtimeText+=`| ${label} / ${phase} / ${op} | ${a.length} | ${ms(median)} | ${ms(Math.max(...sorted))} | ${queue.length?ms(Math.max(...queue.map(x=>x.queueMs))):'—'} | ${queue.length?ms(Math.max(...queue.map(x=>x.executionMs))):'—'} |\n`;
  }
  runtimeText+=`\n${label} 完整索引工作负载：${n(r.sourceRows)} 来源、${n(r.rows)} 已保留 facts、${ms(r.wallMs/1000)} 秒；失败来源 ${r.errors.length}，完整 workspace=false。event loop mean/p95/p99/max=${[r.eventLoop.meanMs,r.eventLoop.p95Ms,r.eventLoop.p99Ms,r.eventLoop.maxMs].map(ms).join('/')} ms；单块 SQL累计观测max=${ms(r.maxChunkSqlMs)} ms。操作失败 ${r.observations.filter(x=>!x.ok).length} 次，完整明细在证据。\n\n`;
}
runtimeText+='全量索引在一个 source EOF 前一直占原 parser slot；yield 能让 metadata/event loop 前进，却不能释放浏览所需 parser queue。基于这里的 queue/execution分解，推荐下一轮评审独立 Search execution lane；不得把秒级排队说成单次 readNode parser执行本身变慢。';
section('runtime',runtimeText);
fs.writeFileSync(target,report);console.log(JSON.stringify({target,bytes:Buffer.byteLength(report)}));
